//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoustonTktServicesAsp_Gourishetty {
    
    
    public partial class ForgotPassword {
        
        /// <summary>
        /// frmForgotPassword control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm frmForgotPassword;
        
        /// <summary>
        /// pgHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HoustonTktServicesAsp_Gourishetty.Header pgHeader;
        
        /// <summary>
        /// spnPassword control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl spnPassword;
        
        /// <summary>
        /// hplBack control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink hplBack;
        
        /// <summary>
        /// PreviousPage property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new HoustonTktServicesAsp_Gourishetty.ForgotPassword1 PreviousPage {
            get {
                return ((HoustonTktServicesAsp_Gourishetty.ForgotPassword1)(base.PreviousPage));
            }
        }
    }
}
